name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up ssh-agent
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-host: ${{ secrets.DOCKER_SSH_HOST }}
          ssh-private-key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      - name: Deploy to swarm
        run: |
          export DOCKER_HOST=ssh://${{ secrets.DOCKER_SSH_USER }}@${{ secrets.DOCKER_SSH_HOST }}
          docker stack deploy --compose-file docker-compose.yml sulin
